- lib/elixir_funcs.sh
instead of checking `STACK` environment variable to close #23
> check if unzip in available

- lib/app_funcs.sh
I had this issue with https://s3.hex.pm.s3.amazonaws.com/installs/hex-0.6.3-dev.ez
> Hex archive can have a different name from hex.ez for custom or interim builds

- lib/app_funcs.sh
My initial build on a [dokku](https://github.com/progrium/dokku) instance failed at creating the .profile.d dir as it already existed. This fixes that.
Thanks for the buildpack :+1:
> mkdir -p .profile.d

- lib/misc_funcs.sh
If you specify multiple config_vars_to_export, only the first is printed as being exported because [Bash is dumb](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html#sect_10_02_02):
> Referring to the content of a member variable of an array without providing an index number is the same as referring to the content of the first element, the one referenced with index number zero.
It still actually exports them all, the "* Config vars" line would just only include the first variable.
This fixes it and prints them all.
> Print all elements of config_vars_to_export

- README.md
- lib/app_funcs.sh
Changes from using `post_compile.sh` to reading the `post_compile` option from the buildpack config.
> Use post_compile option from buildpack config

- README.md
- bin/compile
- lib/app_funcs.sh
> Add post compile hook

- lib/app_funcs.sh
This PR removes the need for a wildcard as per Eric's tip off about other libs having files hex* mix archive files.
* First check for file name in $hex_source if specified
* Then check for first hex file in the new hex-<version>.ez format
* Fall back to old hex.ez file (very unlikely to hit this condition)
\\cc: @ericmj 
P.S: @chrismcg can you try the `HashNuke-hex-path-patch` branch to deploy?
> Check for hex archive file names in order

- README.md
Add-on was removed in https://github.com/HashNuke/heroku-buildpack-elixir/commit/b440237ad702c6917aba4eb83e928df9bac179c7
> Remove mention of PostgreSQL add-on from README

- lib/misc_funcs.sh
In some Heroku-alike environments STACK doesn’t get set; make sure that we don’t use it without quotes to make sure the stack check doesn’t fail in the wrong spot.
> Safely quote uses of $STACK in check_stack()

- elixir_buildpack.config
Elixir 1.2.2 contains a serious build/compile bug that causes random errors, due to some outdated binaries aren't rebuilt. This bug is resolved in version 1.2.3.
We must move the default away from this version 1.2.2, least unsuspecting users using default settings encounter random errors.
> [Urgent] Update Elixir to 1.2.3

- README.md
- elixir_buildpack.config
- lib/erlang_funcs.sh
- lib/path_funcs.sh
It is not guaranteed that the app is installed to /app. Users of buildpacks other than Heroku require applications to be stored at other paths, such as [pkgr](http://github.com/crohr/pkgr) which uses /opt/${APP_NAME}. Furthermore, the source may not be located at /app at compile time, since not every buildpack executor uses a layered filesystem, and so must resort to using a sandbox build directory (some call this the good old days).
This seems to have been broken by f651aacae97df3f28cd86cadef96dcf850e7d0d8.
See https://github.com/crohr/pkgr/issues/93 for the source of this.
> Don't hard-code runtime application path

- lib/app_funcs.sh
This PR ensures that `$full_hex_file_path` is set when `$hex_source` is specified so that it is copied to `~/.mix/archives`
> Fixes local hex path when $hex_source is specified

- README.md
`heroku buildpacks:set` is preferred over the older `BUILDPACK_URL` config var.  This change will also make the instructions match up with our [buildpack documentation](https://devcenter.heroku.com/articles/buildpacks).
> Recommend use of buildpacks:set instead of of older BUILDPACK_URL config var

- bin/compile
- lib/app_funcs.sh
This allows heroku-buildpack-elixir to be used in a multi-buildpack scenario: https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks
This PR supersedes #73.
> Export PATH to erl/elixir/hex for multi-buildpack scenario

- lib/app_funcs.sh
hex is a directory since `.mix/archives` since `1.3.0`
This fix enables working with both Elixir `1.2.x` line with .ez hex archive AND `1.3.0-rc.1`.
> Hex installation fix for Elixir 1.3.0

- lib/misc_funcs.sh
This is a fix for Cloud Foundry which does not pass the env_path during compile step, but env vars can be set before the buildpack runs, without this change we could set MIX_ENV=staging but still the buildpack would run as prod.
It simply checks MIX_ENV is not set before checking the env folder or defaulting to prod.
It does not have any effect if MIX_ENV is not set and would work as before
> check for already set MIX_ENV before defaulting

- bin/detect
Following:
- https://github.com/heroku/heroku-buildpack-ruby/blob/master/bin/detect#L4
- https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/detect#L5
> Follow Heroku convention to use camelcase for platform names

- README.md
- bin/compile
- elixir_buildpack.config
- lib/misc_funcs.sh
Each variable is a file inside `$ENV_DIR` so we load them all up before calling `export_config_vars`
In the future this might need a blacklist of some sort.
> Feature(ENV_VAR): adding `export_default_env_vars`

- README.md
There were some references to `config_vars_to_export` in the `README.md` that didn't get cleaned up in the `export_env_vars` PR.
> Remove dangling references to config_vars_to_export from README.

- lib/app_funcs.sh
Due to registry changes in Hex 0.14.0, the entire `~/.hex` directory should now be copied. Since `registry.ets` would be still be copied, this change is backwards compatible.
See #105 and hexpm/hex@3105cfb19db25e30e93170e6689c6768195fb291.
> Copy entire .hex directory to build directory (#105)

- README.md
- bin/compile
- lib/app_funcs.sh
We where unable to clean certain depencies during the build process, and where forced to add another hook:
`pre_fetch_dependencies`
This solves the current issue for us: 
https://github.com/appsignal/appsignal-elixir/issues/288
> Move precompile hook and add hook before dependency fetch

- lib/elixir_funcs.sh
- lib/erlang_funcs.sh
Printing the download url's to the output can aid in debugging any potential download issues.
> Print download url's for erlang and elixir downloads

- README.md
Use the `hashnuke/elixir` shorthand name in the readme, which points to the version published in the [Buildpack Registry (beta)](https://devcenter.heroku.com/articles/buildpack-registry).
> Updated readme to use Buildpack Registry

- lib/app_funcs.sh
https://github.com/HashNuke/heroku-buildpack-elixir/commit/651bb3d24e9538e158858591499bbcb166ebbb94#diff-affe38b4efd476d398c0a64a202d07d0R156
this changed prod to default, where prior behavior was to write current env ( used in test_compile -> test flow )
> set env to current env rather than prod

- elixir_buildpack.config
Hello :)
I noticed that the default version of elixir is set to `1.5.0` which includes a bug that is noticeable when trying to to deploy a phoenix application:
```
2019-01-03T15:38:37.053305+00:00 app[web.1]: ** (ArgumentError) supervisors expect the child to be a module, a {module, arg} tuple or a map with the child specification, got: {DBConnection.ConnectionPool, {Ecto.Repo.Supervisor, :start_child, [{DBConnection.ConnectionPool, :start_link, [{Postgrex.Protocol, [types: Postgrex.DefaultTypes, repo: PhxHerokuExample.Repo, telemetry_prefix: [:phx_heroku_example, :repo], otp_app: :phx_heroku_example, timeout: 15000, pool_size: 18, ssl: true, username: "yzmhjpskdlwfjb", password: "3ee7f832e5fa8e23d7b83aa6694890876fd837177a5eede0a7346a346fdbe9bc", database: "dltactb6m7fkm", hostname: …
```
> Bump default elixir_version to 1.5.3 to include bug fixes

- elixir_buildpack.config
- lib/erlang_funcs.sh
- lib/misc_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#146 because it introduces an issue https://github.com/HashNuke/heroku-buildpack-elixir/issues/150
> Revert "compute erlang_package_url from configurable host + heroku stack"

- README.md
- bin/compile
- lib/canonical_version.sh
- test/canonical_version_test.sh
Addresses part of #156
I'll submit another pull request that can "alter" the version to the most recent patch if a patch is not specified.
> Friendly error message when erlang version is not supported

- lib/misc_funcs.sh
This PR takes the more restrictive cache clean-up strategy from #146 and applies it to `HEAD`.
This addresses issues with over-zealous cache removal, as seen in mischov/meeseeks#49 and other places that use Rust buildpacks along-side Elixir, while bypassing the problem identified in #150, and resolves #138.
> More restrictive cache clean-up

- README.md
- bin/test
Right now you can't do things like add a coverage report or specify which folders to constrain the testing to. This additional config var, when present, will simply be added to the end of `mix test`. If it is not present, or the value is an empty string, then `mix test` will execute normally (i.e. as though no arguments were passed to it).
I've tested this locally and (a) when using the default config it works and (b) when setting `test_args="--cover"` to the config it properly generate the code coverage report.
> Allow additional test arguments as config vars

- README.md
- lib/app_funcs.sh
Allow setting a custom compilation command using `hook_compile`. See [changed README.md file](https://github.com/HashNuke/heroku-buildpack-elixir/commit/dab040b2c4d6648255bee41b920adcbe1fd480cc) for more details.
* common: add ` --warnings-as-errors` flag to `mix compile` while in Heroku CI to check that the compilation does not have any warnings
* very rare: run the compilation in a single thread (fixes multi-threading compilation issues with some code bases – as temporary solution before fixing the root cause of such problems)
In @socialpaymentsbv we use this patch in the above 2 use cases for [2 months now](https://github.com/socialpaymentsbv/heroku-buildpack-elixir/pull/1).
Tests were ran and the result was:
```sh
git clone https://github.com/socialpaymentsbv/heroku-buildpack-elixir.gi …
```
> Allow setting a custom compilation command using `hook_compile`

- bin/compile
While trying to use private hex repositories. We tried using the `hook_pre_fetch_dependencies` option like this
```
hook_pre_fetch_dependencies="mix hex.organization auth foo --key ${KEY}"
```
But this didn't work, because `${KEY}` is not available before configs are loaded. This change makes it so that env vars are available before the config file is sourced.
> load config after loading env vars so that they can be used in hooks.

- README.md
Release maintenance using tags is no longer performed therefore the README section for "Using older version of buildpack" is updated to be based on "commit SHA" instead on "tag name".
> Update "Using older version of buildpack" README section

- elixir_buildpack.config
- lib/app_funcs.sh
I am not entirely sure about the intention for escaping PATH in `profile.d/<script.sh>` or `export` but esp. for `/export`, it didn't work if `$PATH` is escaped because the `$PATH` in the context of the currently executing buildpack and the one in the context of `export` execution before the next buildpack (but its not clear in the [docs](https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks)) are different.
Based on my test (while I was playing with https://github.com/techgaun/heroku-buildpack-mix-tasks because we wanted to automate couple of custom mix tasks we use internally as part of heroku deployment), I saw that `$PATH` when escaped gets back to the default `$PATH`'s value (which typically is `/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.3.0/ …
> fix issue with correct export of PATH

- README.md
- bin/compile
- lib/app_funcs.sh
[Elixir 1.9](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/) introduced `mix release`. This is a huge improvement for Heroku based deployments because the slug can be compiled once and then deployed to different apps with different configs which will be read at runtime.
This PR adds a new option to build the default release on top of the usual compilation process. After the slug is compiled the release can be run by having `web: _build/prod/rel/{app_name}/bin/{app_name} start`. We at Tallarium already use this setup in all our Elixir Heroku apps.
> add Elixir releases support

- lib/app_funcs.sh
- lib/erlang_funcs.sh
These changes make the buildpack work during Heroku CI as part of a pipeline and with the `ci:debug` cli command.
> erl in ci:debug

- README.md
- elixir_buildpack.config
Fixes `[: =: unary operator expected` when `release` option is not set.
> default value for release option to prevent unary operator error.

- lib/app_funcs.sh
- lib/erlang_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#131
Resolves https://github.com/HashNuke/heroku-buildpack-elixir/issues/167
> Revert "erl in ci:debug"

- README.md
The latest release of this buildpack was in 2015 so you need to use the master branch to be able to use the Elixir releases support.
> Add note about releases

- README.md
- lib/canonical_version.sh
- lib/erlang_funcs.sh
Uses hex's otp builds for heroku-20 and gigalixir-20 and continues using the same builds for all other stacks. Eventually, we'll try to migrate all builds to hex's.
@KazW do you mind taking a look at this?
> Support heroku-20 and gigalixir-20

- lib/elixir_funcs.sh
- lib/erlang_funcs.sh
- lib/misc_funcs.sh
- lib/path_funcs.sh
This way the cache can be reliably cleared without having to maintain a list of all the different cache directories between multiple files.
The erlang cache wasn't changing when the stack changed due to the `clean_cache` not knowing that there were files for Erlang in `${cache_path}/OTP-*.zip` (and elixir in `${cache_path}/elixir*.zip`) .
This also adds a `elixir_cache_path` and a `erlang_cache_path` functions for allowing us to keep to track of the Elixir/Erlang caches in one central place.
fixes #197
> place all stack-dependent cache folders under one root folder

- lib/app_funcs.sh
- lib/erlang_funcs.sh
fixes #194
Newer versions of the Heroku build system build the app in `/app` rather
than a tmp directory. If this is the case (the BUILD_DIR argument is the
same as `/app`), don't copy hex or other files over as they are already
in place.
https://github.com/HashNuke/heroku-buildpack-elixir/issues/194#issuecomment-800425532
> fix compatibilities when BUILD_DIR argument is /app

- lib/app_funcs.sh
- lib/erlang_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#200
Sorry to revert, but I'm getting a lot of reports from customers that this has broken the build with the following error.
remote: /tmp/build/.platform_tools/elixir/bin/elixir: 230: exec: erl: not found
I'm also not 100% sure if all of the pull request comments were addressed, which is why I didn't merge it before.
> Revert "fix compatibilities when BUILD_DIR argument is /app"

- bin/compile
- lib/app_funcs.sh
- lib/elixir_funcs.sh
- lib/erlang_funcs.sh
- lib/misc_funcs.sh
- lib/path_funcs.sh
tl;dr:
- Instead of relying on Mix's default behavior of installing to `$HOME/.mix`, the buildpack sets `$MIX_HOME` to a directory controlled by the buildpack when running `mix`
- Instead of relying on Hex's default behavior of installing to `$HOME/.hex`, the buildpack sets `$HEX_HOME` to a directory controlled by the buildpack when running `hex`
- The buildpack now exports `HEX_HOME` and `MIX_HOME` if they are not set as configuration variables.
By using `MIX_HOME` and `HEX_HOME`, we can consolidate some logic for transferring mix/hex files in and out of the cache and app build directory.
This should allow the buildpack to work in the new build system and the old build system since this buildpack no longer relies on what the value of `HOME` is at either build time or runtime.
fixes #194 …
> use MIX_HOME,HEX_HOME when installing mix/hex dependencies

- README.md
- lib/canonical_version.sh
Fixes #210 
Heroku recently released the new stack-22 based on Ubuntu 22.04. We just need to add the OTP build urls for Ubuntu 22.04 and we're good to go. I've tested the changes with my fork of this repo and successfully deployed a stack-22 app.
Merging this would be appreciated.
Best regards,
Kai
> Add support for Heroku Stack-22.
