HashNuke/heroku-buildpack-elixir

- README.md
- elixir_buildpack.config
* Update the defaults to Erlang 17.5 and Elixir 1.0.4
* Update the examples in README with the latest versions
> Use Erlang 17.5 and Elixir 1.0.4

- bin/compile
The loop is just eval-ing the list of functions. Might as well call the functions directly.
It feels very funny that I never noticed it when writing it.
P.S: Please do let me know if removing this is wrong. I'm as sleepy as I was when I wrote the loop.
> Remove unnecessary loop in bin/compile

- lib/misc_funcs.sh
Just cleaning up some funs that are unused
> Remove unused github_download() and try_run()

- lib/app_funcs.sh
Tweak the logic and ensure the same level of path is used
> Hash nuke hex path patch fix

- elixir_buildpack.config
> Update to Elixir 1.2.0

- README.md
- bin/compile
- lib/app_funcs.sh
A very lazy pull request that more-or-less copy and pastes the changes from #39.
I needed this because one of the templates for my phoenix app is generated by another command that must be run before the application compiles (otherwise, I compile with a missing template..). Running off my fork, but thought it might be useful to others as well.
> Add precompile hook

- lib/misc_funcs.sh
> Fixes multiline config vars

- elixir_buildpack.config
1.2.x doesn't work for :gen_stage
> Use the latest version of elixir by default (1.3.4)

- elixir_buildpack.config
It might make sense to upgrade to Erlang 20 and Elixir 1.5.0
> use latest erlang and elixir

- README.md
This will help someone that doesn't know which versions are valid to include. Also added a link to Elixir and Erlang compatibility since that is useful when determining the versions to use.
> Add the the location of the lists of available versions to the README

- elixir_buildpack.config
- lib/erlang_funcs.sh
- lib/misc_funcs.sh
This PR is intended to make the buildpack more configurable by end users who may run their own Erlang build hosts 😄
> compute erlang_package_url from configurable host + heroku stack

- lib/app_funcs.sh
- lib/elixir_funcs.sh
> Make sure that folders exist and copy content only

- README.md
Follow up on https://github.com/HashNuke/heroku-buildpack-elixir/pull/143#discussion_r341272266.
> Recommend using a specific version of buildpack

- README.md
closes HashNuke/heroku-buildpack-elixir#179
closes HashNuke/heroku-buildpack-elixir-otp-builds#62
closes HashNuke/heroku-buildpack-elixir#177
> Add Heroku 20 and Cloud Native info

- lib/erlang_funcs.sh
- lib/misc_funcs.sh
- lib/path_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#182
> Revert "Removes unused erlang cache to save disk space"

- lib/erlang_funcs.sh
- lib/misc_funcs.sh
- lib/path_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#184
> Revert "Revert "Removes unused erlang cache to save disk space""

- lib/erlang_funcs.sh
- lib/misc_funcs.sh
- lib/path_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#186
> Revert "Revert "Revert "Removes unused erlang cache to save disk space"""

- lib/misc_funcs.sh
- lib/path_funcs.sh
This is the second attempt and hopefully will not cause https://github.com/HashNuke/heroku-buildpack-elixir/issues/183 to reoccur.
> Remove erlang build dir cache since we do not use it

- bin/compile
- bin/detect
- bin/test
- bin/test-compile
> ensure bash exits with non-zero status code if build fails

- README.md
- bin/compile
- lib/misc_funcs.sh
Reverts HashNuke/heroku-buildpack-elixir#206
> Revert "Support app_relative_path"

- bin/compile
- elixir_buildpack.config
- lib/canonical_version.sh
- lib/misc_funcs.sh
> Friendly error message for unsupported or incorrectly formatted elixir
